import type { PageContentDocument } from "@/types/pageContent";

export const HOME_SECTION_ORDER = [
  "hero",
  "features",
  "recommendedTrains",
  "routesSection",
  "events",
  "inspiration",
  "testimonials",
  "support",
  "blogInvite",
  "verified",
] as const;

export const homePageDefaults: PageContentDocument = {
  version: 1,
  sectionOrder: [...HOME_SECTION_ORDER],
  sections: {
    hero: {
      visible: true,
      fields: {
        title: "Путешествие это легко!",
        titleColor: "",
        videoTrain: "",
        videoFlight: "",
        videoBus: "",
      },
    },
    features: {
      visible: true,
      fields: {
        title: "Почему выбирают TudaSuda?",
        subtitle: "Всё для комфортного путешествия туда и обратно",
        titleColor: "",
        subtitleColor: "",
        items: [
          {
            title: "Всё в одном месте",
            description: "Поиск, бронирование и оплата за минуты",
            fullDescription:
              "TudaSuda объединяет все необходимые функции для путешествий в одном удобном интерфейсе. Вы можете найти билеты, выбрать места, оплатить заказ и получить электронные билеты — всё это без перехода на другие сайты. Наш сервис работает с ж/д, авиа и автобусными перевозчиками, предоставляя единую точку доступа ко всем видам транспорта.",
            bgColor: "",
            iconBgColor: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            title: "Лучшая цена",
            description: "Гарантируем выгодные тарифы без скрытых платежей",
            fullDescription:
              "Мы сравниваем цены со всех доступных источников и гарантируем, что вы получите лучшую цену на рынке. Прозрачные тарифы без скрытых комиссий и дополнительных платежей. Если вы найдёте дешевле на другом сайте — мы вернём разницу. Наша система автоматически отслеживает изменения цен и предлагает наиболее выгодные варианты.",
            bgColor: "",
            iconBgColor: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            title: "Поддержка 24/7",
            description: "Помогаем в любое время, отвечаем за 2 минуты",
            fullDescription:
              "Наша служба поддержки работает круглосуточно, семь дней в неделю. Мы помогаем с бронированием, изменениями, возвратами и любыми вопросами. Среднее время ответа — менее 2 минут. С нами можно связаться через чат, телефон или email. Наши специалисты всегда готовы помочь вам с любыми вопросами, связанными с путешествиями.",
            bgColor: "",
            iconBgColor: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            title: "Электронные билеты",
            description: "Мгновенная выдача и быстрая регистрация",
            fullDescription:
              "Получите электронные билеты мгновенно после оплаты. Не нужно ждать доставки или идти в кассу — билеты приходят на вашу почту и сохраняются в личном кабинете. Быстрая регистрация на рейс прямо через наш сервис. Все документы хранятся в безопасном облачном хранилище, доступ к которому у вас есть в любое время.",
            bgColor: "",
            iconBgColor: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            title: "Готовые маршруты",
            description: "Проверенные маршруты по всей России",
            fullDescription:
              "Мы предлагаем готовые маршруты по регионам России, которые были проверены тревел-блогерами и журналистами. Каждый маршрут включает подробную информацию о достопримечательностях, удобствах и советы от опытных путешественников. Вы можете выбрать готовый маршрут или создать свой собственный на основе наших рекомендаций.",
            bgColor: "",
            iconBgColor: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            title: "Путеводители",
            description: "Подробные обзоры городов и достопримечательностей",
            fullDescription:
              "Подробные путеводители с обзорами городов и достопримечательностей помогут вам спланировать идеальное путешествие. Мы собрали информацию о лучших местах для посещения, ресторанах, отелях и развлечениях. Наши путеводители регулярно обновляются и содержат актуальную информацию от местных экспертов и путешественников.",
            bgColor: "",
            iconBgColor: "",
            titleColor: "",
            descriptionColor: "",
          },
        ],
      },
    },
    recommendedTrains: {
      visible: true,
      fields: {
        title: "Горящие направления",
        subtitle: "Специальные предложения и скидки на популярные маршруты",
        titleColor: "",
        subtitleColor: "",
        items: [
          {
            from: "Москва",
            to: "Санкт-Петербург",
            image: "",
            oldPrice: "3 500 ₽",
            newPrice: "2 800 ₽",
            discount: 20,
            tag: "Популярно",
            description: "Быстрое и комфортное путешествие",
            href: "",
          },
          {
            from: "Москва",
            to: "Казань",
            image: "",
            oldPrice: "4 200 ₽",
            newPrice: "2 940 ₽",
            discount: 30,
            tag: "Горящее",
            description: "Скидка на билеты до конца месяца",
            href: "",
          },
          {
            from: "Санкт-Петербург",
            to: "Москва",
            image: "",
            oldPrice: "3 800 ₽",
            newPrice: "3 040 ₽",
            discount: 20,
            tag: "Популярно",
            description: "Ежедневные рейсы",
            href: "",
          },
          {
            from: "Москва",
            to: "Великий Новгород",
            image: "",
            oldPrice: "2 500 ₽",
            newPrice: "1 500 ₽",
            discount: 40,
            tag: "Бюджетно",
            description: "Отличная цена для путешествия",
            href: "",
          },
          {
            from: "Санкт-Петербург",
            to: "Карелия",
            image: "",
            oldPrice: "3 200 ₽",
            newPrice: "2 240 ₽",
            discount: 30,
            tag: "Экскурсии",
            description: "Красивые пейзажи и природа",
            href: "",
          },
          {
            from: "Москва",
            to: "Сочи",
            image: "",
            oldPrice: "5 500 ₽",
            newPrice: "3 850 ₽",
            discount: 30,
            tag: "Горящее",
            description: "Отдых у моря по выгодной цене",
            href: "",
          },
          {
            from: "Казань",
            to: "Москва",
            image: "",
            oldPrice: "4 000 ₽",
            newPrice: "2 800 ₽",
            discount: 30,
            tag: "Популярно",
            description: "Комфортные поезда",
            href: "",
          },
          {
            from: "Москва",
            to: "Нижний Новгород",
            image: "",
            oldPrice: "2 800 ₽",
            newPrice: "1 680 ₽",
            discount: 40,
            tag: "Бюджетно",
            description: "Экономия до 40%",
            href: "",
          },
        ],
      },
    },
    routesSection: {
      visible: true,
      fields: {
        title: "Популярные направления",
        subtitle: "Самые востребованные маршруты с актуальными ценами",
        titleColor: "",
        subtitleColor: "",
        routes: [
          {
            from: "Москва",
            to: "Санкт-Петербург",
            minPrice: 2950,
            isPopular: true,
            duration: "3ч 55м",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
          {
            from: "Москва",
            to: "Казань",
            minPrice: 1850,
            isPopular: true,
            duration: "11ч 30м",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
          {
            from: "Москва",
            to: "Нижний Новгород",
            minPrice: 650,
            isPopular: false,
            duration: "3ч 40м",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
          {
            from: "Санкт-Петербург",
            to: "Москва",
            minPrice: 2950,
            isPopular: true,
            duration: "3ч 55м",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
          {
            from: "Казань",
            to: "Москва",
            minPrice: 1850,
            isPopular: false,
            duration: "11ч 30м",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
          {
            from: "Тверь",
            to: "Москва",
            minPrice: 550,
            isPopular: false,
            duration: "1ч 40м",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
          {
            from: "Москва",
            to: "Сочи",
            minPrice: 2500,
            isPopular: true,
            duration: "24ч",
            borderColor: "",
            textColor: "",
            priceColor: "",
          },
        ],
      },
    },
    events: {
      visible: true,
      fields: {
        title: "Повод для путешествия",
        subtitle: "10 событий, ради которых стоит ровнуть в путь",
        moreLabel: "Ещё",
        moreHref: "/blog",
        titleColor: "",
        subtitleColor: "",
        items: [
          {
            city: "Краснодар",
            age: "12+",
            price: "от 2500",
            artist: "ARTIC & ASTI",
            date: "23 октября",
            venue: "Ледовый дворец",
            color: "from-red-900 to-red-700",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Казань",
            age: "18+",
            price: "от 2500",
            artist: "Anna Asti. Шоу «Царица»",
            date: "9 ноября",
            venue: "Татнефть Арена",
            color: "from-pink-700 to-pink-500",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Петербург",
            age: "12+",
            price: "от 2500",
            artist: "Баста",
            date: "20 декабря",
            venue: "Газпром Арена",
            color: "from-orange-800 to-blue-900",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Москва",
            age: "16+",
            price: "от 3000",
            artist: "Сергей Лазарев",
            date: "5 ноября",
            venue: "Crocus City Hall",
            color: "from-purple-900 to-purple-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Екатеринбург",
            age: "18+",
            price: "от 2800",
            artist: "Макс Корж",
            date: "15 ноября",
            venue: "КРК Уралец",
            color: "from-blue-900 to-blue-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Нижний Новгород",
            age: "12+",
            price: "от 2200",
            artist: "Земфира",
            date: "18 ноября",
            venue: "КЗ Нагорный",
            color: "from-green-900 to-green-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Новосибирск",
            age: "16+",
            price: "от 2600",
            artist: "Би-2",
            date: "25 ноября",
            venue: "Дворец Спорта",
            color: "from-yellow-900 to-yellow-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Сочи",
            age: "18+",
            price: "от 3500",
            artist: "Мот",
            date: "1 декабря",
            venue: "Фестивальный",
            color: "from-teal-900 to-teal-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Уфа",
            age: "12+",
            price: "от 2400",
            artist: "Полина Гагарина",
            date: "8 декабря",
            venue: "Конгресс-Холл",
            color: "from-indigo-900 to-indigo-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
          {
            city: "Владивосток",
            age: "16+",
            price: "от 2900",
            artist: "Монеточка",
            date: "12 декабря",
            venue: "Фетисов Арена",
            color: "from-rose-900 to-rose-600",
            bgColor: "",
            image: "",
            href: "",
            textColor: "",
          },
        ],
      },
    },
    inspiration: {
      visible: true,
      fields: {
        title: "Вдохновение для следующей поездки",
        subtitle: "Найдите идеи и направления",
        titleColor: "",
        subtitleColor: "",
        items: [
          {
            name: "Душевная Армения",
            description: "Ереван, Севан и древние монастыри",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Отпуск в Китае",
            description: "Что стоит знать перед первой поездкой",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Маршрут по Карелии",
            description: "Главные места для знакомства с республикой",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Золотое кольцо России",
            description: "Древние города и православные святыни",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Байкал зимой",
            description: "Невероятная красота ледяного озера",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Камчатка",
            description: "Вулканы, гейзеры и дикая природа",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Алтай",
            description: "Горы, озёра и бескрайние степи",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Крым",
            description: "Южное побережье и горные тропы",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Якутия",
            description: "Полюс холода и северное сияние",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
          {
            name: "Кавказ",
            description: "Эльбрус и горные аулы",
            image: "",
            href: "",
            titleColor: "",
            descriptionColor: "",
          },
        ],
      },
    },
    testimonials: {
      visible: true,
      fields: {
        title: "Живые истории путешествий",
        subtitle: "Реальные люди, реальные эмоции, реальные путешествия",
        titleColor: "",
        subtitleColor: "",
        items: [
          {
            id: 1,
            name: "Марина",
            avatar: "",
            photo: "",
            text: "Вот такой вид из окна поезда Москва — Санкт-Петербург",
            route: "Москва → Санкт-Петербург",
            date: "15 ноября 2024",
            body: "Вот такой вид из окна поезда Москва — Санкт-Петербург",
            gallery: [],
          },
          {
            id: 2,
            name: "Алексей",
            avatar: "",
            photo: "",
            text: "Поездка прошла идеально, буду ездить через TudaSuda!",
            route: "Москва → Казань",
            date: "12 ноября 2024",
            body: "Поездка прошла идеально, буду ездить через TudaSuda!",
            gallery: [],
          },
          {
            id: 3,
            name: "Елена",
            avatar: "",
            photo: "",
            text: "Удобные места, чисто, комфортно. Всё как на фото!",
            route: "Санкт-Петербург → Москва",
            date: "10 ноября 2024",
            body: "Удобные места, чисто, комфортно. Всё как на фото!",
            gallery: [],
          },
          {
            id: 4,
            name: "Дмитрий",
            avatar: "",
            photo: "",
            text: "Невероятные виды! Поездка на Байкал — это что-то особенное",
            route: "Иркутск → Байкал",
            date: "8 ноября 2024",
            body: "Невероятные виды! Поездка на Байкал — это что-то особенное",
            gallery: [],
          },
          {
            id: 5,
            name: "Анна",
            avatar: "",
            photo: "",
            text: "Отличная цена и сервис. Рекомендую всем друзьям!",
            route: "Москва → Великий Новгород",
            date: "5 ноября 2024",
            body: "Отличная цена и сервис. Рекомендую всем друзьям!",
            gallery: [],
          },
          {
            id: 6,
            name: "Сергей",
            avatar: "",
            photo: "",
            text: "Дальневосточные приключения начались! Владивосток ждёт",
            route: "Москва → Владивосток",
            date: "3 ноября 2024",
            body: "Дальневосточные приключения начались! Владивосток ждёт",
            gallery: [],
          },
          {
            id: 7,
            name: "Ольга",
            avatar: "",
            photo: "",
            text: "Европейский колорит в России. Калининград — это магия!",
            route: "Москва → Калининград",
            date: "1 ноября 2024",
            body: "Европейский колорит в России. Калининград — это магия!",
            gallery: [],
          },
          {
            id: 8,
            name: "Иван",
            avatar: "",
            photo: "",
            text: "Красивые пейзажи Карелии. Природа здесь просто потрясающая",
            route: "Санкт-Петербург → Карелия",
            date: "29 октября 2024",
            body: "Красивые пейзажи Карелии. Природа здесь просто потрясающая",
            gallery: [],
          },
          {
            id: 9,
            name: "Татьяна",
            avatar: "",
            photo: "",
            text: "Быстро, удобно, без проблем. TudaSuda — мой выбор!",
            route: "Санкт-Петербург → Москва",
            date: "27 октября 2024",
            body: "Быстро, удобно, без проблем. TudaSuda — мой выбор!",
            gallery: [],
          },
          {
            id: 10,
            name: "Михаил",
            avatar: "",
            photo: "",
            text: "Белые ночи в Питере. Это нужно видеть своими глазами!",
            route: "Москва → Санкт-Петербург",
            date: "25 октября 2024",
            body: "Белые ночи в Питере. Это нужно видеть своими глазами!",
            gallery: [],
          },
          {
            id: 11,
            name: "Наталья",
            avatar: "",
            photo: "",
            text: "Комфортная поездка, отличный сервис. Обязательно вернусь!",
            route: "Москва → Сочи",
            date: "23 октября 2024",
            body: "Комфортная поездка, отличный сервис. Обязательно вернусь!",
            gallery: [],
          },
        ],
      },
    },
    support: {
      visible: true,
      fields: {
        title: "Умный бот-помощник 24/7",
        subtitle: "Решаем вопросы быстро и эффективно, работаем круглосуточно",
        titleColor: "",
        subtitleColor: "",
        textColor: "",
        description1:
          "Наш умный бот-помощник использует технологии искусственного интеллекта для быстрого решения ваших вопросов. Он понимает контекст, помнит историю диалога и может помочь с выбором билетов, маршрутов и планированием путешествий.",
        description2:
          "Если бот не сможет решить вопрос самостоятельно, он мгновенно подключит живого оператора, который продолжит диалог без потери контекста. Все ваши данные защищены и обрабатываются в соответствии с требованиями безопасности.",
        contactHeading: "Выберите способ связи",
        chatCta: "Открыть чат с ботом",
      },
    },
    blogInvite: {
      visible: true,
      fields: {
        badge: "Для читателей",
        title: "Зачем читать блог TudaSuda",
        titleColor: "",
        textColor: "",
        paragraph1:
          "Мы пишем о том, как проще планировать поездки по России и за её пределами: от выбора билетов и отелей до документов и бюджета. Статьи редакции основаны на опыте команды и обратной связи пассажиров.",
        paragraph2:
          "Блог дополняет справочник и путеводитель: здесь больше про идеи для поездок, обновления сервиса и практичные советы в одном месте.",
        ctaLabel: "Перейти в блог",
        ctaHref: "/blog",
      },
    },
    verified: {
      visible: true,
      fields: {
        badgeLeft: "Проверено",
        badgeRight: "TudaSuda",
        title: "Готовые маршруты для путешествий",
        titleColor: "",
        description:
          "Проверенные тревел-блогерами и журналистами маршруты по всей России. Каждый маршрут включает подробную информацию о достопримечательностях и советы от опытных путешественников.",
        descriptionColor: "",
        ctaLabel: "Все маршруты",
        ctaHref: "/routes/list",
        polaroids: [],
      },
    },
  },
};
